
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - ".*Tests\\.swift"
  - MenuAppTDDTests
  - MenuAppTDDAPIEndToEndTests

force_cast: warning
force_try: warning

line_length:
  warning: 180
  error: 500

file_length:
  warning: 600
  error: 1000

function_body_length:
  warning: 40
  error: 120

opt_in_rules:
  - empty_count
  - force_unwrapping
  - legacy_constant
  - legacy_constructor
  - private_action
  - private_outlet

disabled_rules:
  - vertical_whitespace
  - trailing_whitespace
  - identifier_name

