# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MenuAppTDD' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MenuAppTDD
  pod 'SwiftLint', '0.39.1'

  target 'MenuAppTDDTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MenuAppTDDUITests' do
    # Pods for testing
  end

end
